package: bloecks
version: '1.3.8'
author: 'FriendsOfREDAXO'
supportpage: https://github.com/FriendsOfREDAXO/bloecks

page:
    title: translate:navigation
    perm: bloecks[]
    pjax: false
    icon: rex-icon rex-icon-template

requires:
    packages:
        structure/content: '>=2.1.0'
    redaxo: ^5.2.0
