package: bloecks
version: '4.0.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/bloecks

page:
    title: translate:navigation
    perm: bloecks[]
    pjax: false
    icon: rex-icon rex-icon-template
    subpages:
        overview:
            title: 'translate:overview'
        docs:
            title: translate:docs
            subPath: README.developers.md
            icon: rex-icon fa-book
            itemclass: pull-right

requires:
    packages:
        structure/content: '^2.1.0'
    redaxo: ^5.14.1
    php: '>=8.1'

installer_ignore:
    - node_modules
